services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://taller_user:taller_password@db:5432/taller_db?schema=public"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: node dist/server.js  # o el entrypoint correcto si compilas TypeScript

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
