version: '3.8'

services:
  db:
    image: postgres:15
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: taller_user
      POSTGRES_PASSWORD: taller_password
      POSTGRES_DB: taller_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taller_user -d taller_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://taller_user:taller_password@db:5432/taller_db?schema=public"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
volumes:
  postgres_data:
